// Mock data for development without Supabase connection
import type { Degree, PartnerUniversity, FAQ } from '@/lib/supabase/types';

export const mockDegrees: Degree[] = [
  {
    id: '1',
    name: 'MBA',
    full_name: 'Master of Business Administration',
    slug: 'mba',
    description: 'The MBA program is designed to develop managerial skills and business acumen. Learn strategic thinking, leadership, and decision-making from industry experts.',
    icon_url: null,
    banner_image: null,
    category: 'postgraduate',
    stream: 'Management',
    duration_months: 24,
    duration_text: '2 Years',
    mode: 'online',
    fee_range_min: 80000,
    fee_range_max: 250000,
    emi_available: true,
    emi_starting: 4999,
    eligibility_criteria: 'Graduation with 50% marks from a recognized university',
    min_qualification: 'graduate',
    work_experience_required: false,
    min_work_experience: null,
    career_paths: ['Marketing Manager', 'Finance Analyst', 'HR Manager', 'Operations Manager', 'Business Consultant'],
    avg_salary_range: '6-15 LPA',
    top_recruiters: ['TCS', 'Infosys', 'Wipro', 'Accenture', 'Deloitte', 'Amazon'],
    placement_assistance: true,
    highlights: ['UGC-Recognized Universities', 'Industry-Relevant Curriculum', '100% Online Learning', 'Placement Assistance', 'EMI Options Available'],
    syllabus_overview: 'The curriculum covers core management subjects including Marketing, Finance, HR, Operations, and Strategy along with specialization electives.',
    brochure_url: null,
    meta_title: 'Online MBA Program | My College Sathi',
    meta_description: 'Pursue your Online MBA from top UGC-recognized universities. Flexible learning with placement assistance.',
    is_featured: true,
    is_popular: true,
    display_order: 1,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'BBA',
    full_name: 'Bachelor of Business Administration',
    slug: 'bba',
    description: 'BBA program provides a strong foundation in business and management principles, preparing students for entry-level management positions or higher studies.',
    icon_url: null,
    banner_image: null,
    category: 'undergraduate',
    stream: 'Management',
    duration_months: 36,
    duration_text: '3 Years',
    mode: 'online',
    fee_range_min: 60000,
    fee_range_max: 180000,
    emi_available: true,
    emi_starting: 3499,
    eligibility_criteria: '12th Pass with 50% marks from any stream',
    min_qualification: '12th_pass',
    work_experience_required: false,
    min_work_experience: null,
    career_paths: ['Business Analyst', 'Marketing Executive', 'Sales Manager', 'HR Executive'],
    avg_salary_range: '3-8 LPA',
    top_recruiters: ['Reliance', 'Tata', 'Aditya Birla', 'Mahindra', 'L&T'],
    placement_assistance: true,
    highlights: ['Foundation for MBA', 'Industry Exposure', 'Internship Opportunities', 'Soft Skills Development'],
    syllabus_overview: 'Covers business fundamentals, accounting, marketing, finance, and organizational behavior.',
    brochure_url: null,
    meta_title: 'Online BBA Program | My College Sathi',
    meta_description: 'Start your management journey with Online BBA from recognized universities.',
    is_featured: true,
    is_popular: true,
    display_order: 2,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'MCA',
    full_name: 'Master of Computer Applications',
    slug: 'mca',
    description: 'MCA program provides advanced knowledge in computer applications, programming, and software development. Ideal for those looking to build a career in IT.',
    icon_url: null,
    banner_image: null,
    category: 'postgraduate',
    stream: 'Technology',
    duration_months: 24,
    duration_text: '2 Years',
    mode: 'online',
    fee_range_min: 70000,
    fee_range_max: 200000,
    emi_available: true,
    emi_starting: 4499,
    eligibility_criteria: 'BCA/B.Sc (CS/IT) with 50% marks or equivalent',
    min_qualification: 'graduate',
    work_experience_required: false,
    min_work_experience: null,
    career_paths: ['Software Developer', 'System Analyst', 'Database Administrator', 'Cloud Engineer', 'DevOps Engineer'],
    avg_salary_range: '5-12 LPA',
    top_recruiters: ['Google', 'Microsoft', 'Amazon', 'TCS', 'Infosys', 'HCL'],
    placement_assistance: true,
    highlights: ['Latest Technology Stack', 'Hands-on Projects', 'Industry Certifications', 'Virtual Labs'],
    syllabus_overview: 'Covers programming languages, data structures, algorithms, databases, cloud computing, and software engineering.',
    brochure_url: null,
    meta_title: 'Online MCA Program | My College Sathi',
    meta_description: 'Advance your IT career with Online MCA from top universities.',
    is_featured: true,
    is_popular: true,
    display_order: 3,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'BCA',
    full_name: 'Bachelor of Computer Applications',
    slug: 'bca',
    description: 'BCA program provides foundational knowledge in computer science and applications, preparing students for entry-level IT positions.',
    icon_url: null,
    banner_image: null,
    category: 'undergraduate',
    stream: 'Technology',
    duration_months: 36,
    duration_text: '3 Years',
    mode: 'online',
    fee_range_min: 50000,
    fee_range_max: 150000,
    emi_available: true,
    emi_starting: 2999,
    eligibility_criteria: '12th Pass with Mathematics',
    min_qualification: '12th_pass',
    work_experience_required: false,
    min_work_experience: null,
    career_paths: ['Junior Developer', 'IT Support Engineer', 'Web Developer', 'QA Tester'],
    avg_salary_range: '3-6 LPA',
    top_recruiters: ['Cognizant', 'Tech Mahindra', 'Mindtree', 'Mphasis', 'Hexaware'],
    placement_assistance: true,
    highlights: ['Programming Fundamentals', 'Web Technologies', 'Database Management', 'Gateway to MCA'],
    syllabus_overview: 'Covers programming basics, web development, database management, and software fundamentals.',
    brochure_url: null,
    meta_title: 'Online BCA Program | My College Sathi',
    meta_description: 'Start your IT career with Online BCA from recognized universities.',
    is_featured: true,
    is_popular: true,
    display_order: 4,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'M.Com',
    full_name: 'Master of Commerce',
    slug: 'mcom',
    description: 'M.Com program provides advanced knowledge in commerce, accounting, and finance. Ideal for those pursuing careers in accounting, banking, and finance.',
    icon_url: null,
    banner_image: null,
    category: 'postgraduate',
    stream: 'Commerce',
    duration_months: 24,
    duration_text: '2 Years',
    mode: 'online',
    fee_range_min: 40000,
    fee_range_max: 120000,
    emi_available: true,
    emi_starting: 2999,
    eligibility_criteria: 'B.Com or equivalent with 50% marks',
    min_qualification: 'graduate',
    work_experience_required: false,
    min_work_experience: null,
    career_paths: ['Accountant', 'Financial Analyst', 'Tax Consultant', 'Auditor', 'Banking Professional'],
    avg_salary_range: '4-10 LPA',
    top_recruiters: ['Deloitte', 'EY', 'KPMG', 'PwC', 'HDFC Bank', 'ICICI Bank'],
    placement_assistance: true,
    highlights: ['CA/CMA Foundation', 'Practical Accounting', 'GST & Taxation'],
    syllabus_overview: 'Covers advanced accounting, taxation, auditing, financial management, and business law.',
    brochure_url: null,
    meta_title: 'Online M.Com Program | My College Sathi',
    meta_description: 'Advance your commerce career with Online M.Com from top universities.',
    is_featured: false,
    is_popular: true,
    display_order: 5,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'B.Com',
    full_name: 'Bachelor of Commerce',
    slug: 'bcom',
    description: 'B.Com program provides foundational knowledge in commerce, accounting, and business. Ideal foundation for CA, CMA, or banking careers.',
    icon_url: null,
    banner_image: null,
    category: 'undergraduate',
    stream: 'Commerce',
    duration_months: 36,
    duration_text: '3 Years',
    mode: 'online',
    fee_range_min: 30000,
    fee_range_max: 90000,
    emi_available: true,
    emi_starting: 1999,
    eligibility_criteria: '12th Pass with 50% marks (Commerce preferred)',
    min_qualification: '12th_pass',
    work_experience_required: false,
    min_work_experience: null,
    career_paths: ['Accountant', 'Bank Clerk', 'Tax Assistant', 'Audit Trainee'],
    avg_salary_range: '2.5-5 LPA',
    top_recruiters: ['SBI', 'Bank of Baroda', 'Axis Bank', 'Yes Bank'],
    placement_assistance: true,
    highlights: ['Foundation for CA/CMA', 'Accounts & Finance Focus', 'Banking Sector Ready'],
    syllabus_overview: 'Covers accounting principles, business economics, corporate law, and financial management.',
    brochure_url: null,
    meta_title: 'Online B.Com Program | My College Sathi',
    meta_description: 'Start your commerce journey with Online B.Com from recognized universities.',
    is_featured: false,
    is_popular: true,
    display_order: 6,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const mockPartnerUniversities: PartnerUniversity[] = [
  {
    id: '1',
    name: 'Manipal University Online',
    short_name: 'Manipal',
    logo_url: '/images/universities/manipal.webp',
    website_url: 'https://www.manipal.edu',
    accreditations: [{ type: 'NAAC', grade: 'A+' }, { type: 'UGC' }, { type: 'NIRF' }],
    established_year: 1953,
    display_order: 1,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Amity University Online',
    short_name: 'Amity',
    logo_url: '/images/universities/amity.png',
    website_url: 'https://www.amity.edu',
    accreditations: [{ type: 'NAAC', grade: 'A+' }, { type: 'UGC' }, { type: 'AICTE' }],
    established_year: 2005,
    display_order: 2,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Jain University Online',
    short_name: 'Jain',
    logo_url: '/images/universities/jainonline.jpg',
    website_url: 'https://www.jainuniversity.ac.in',
    accreditations: [{ type: 'NAAC', grade: 'A' }, { type: 'UGC' }],
    established_year: 1990,
    display_order: 3,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Chandigarh University Online',
    short_name: 'CU',
    logo_url: '/images/universities/cu.jpg',
    website_url: 'https://www.cuchd.in',
    accreditations: [{ type: 'NAAC', grade: 'A+' }, { type: 'UGC' }, { type: 'NIRF' }],
    established_year: 2012,
    display_order: 4,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'LPU Online',
    short_name: 'LPU',
    logo_url: '/images/universities/lpu.png',
    website_url: 'https://www.lpu.in',
    accreditations: [{ type: 'NAAC', grade: 'A++' }, { type: 'UGC' }],
    established_year: 2005,
    display_order: 5,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'NMIMS Online',
    short_name: 'NMIMS',
    logo_url: '/images/universities/nmims.webp',
    website_url: 'https://www.nmims.edu',
    accreditations: [{ type: 'NAAC', grade: 'A+' }, { type: 'UGC' }],
    established_year: 1981,
    display_order: 6,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '7',
    name: 'Dr. D. Y. Patil Vidyapeeth Online',
    short_name: 'DY Patil',
    logo_url: '/images/universities/dypatil.png',
    website_url: 'https://dpu.edu.in',
    accreditations: [{ type: 'NAAC', grade: 'A++' }, { type: 'UGC' }],
    established_year: 2003,
    display_order: 7,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '8',
    name: 'UPES Online',
    short_name: 'UPES',
    logo_url: '/images/universities/upes.png',
    website_url: 'https://www.upes.ac.in',
    accreditations: [{ type: 'NAAC', grade: 'A' }, { type: 'UGC' }],
    established_year: 2003,
    display_order: 8,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '9',
    name: 'Galgotias University Online',
    short_name: 'Galgotias',
    logo_url: '/images/universities/galgotias.jpeg',
    website_url: 'https://www.galgotiasuniversity.edu.in',
    accreditations: [{ type: 'NAAC', grade: 'A+' }, { type: 'UGC' }],
    established_year: 2011,
    display_order: 9,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const mockFAQs: FAQ[] = [
  {
    id: '1',
    degree_id: null,
    question: 'Are online degrees valid in India?',
    answer: 'Yes, online degrees from UGC-recognized universities are completely valid and have the same recognition as regular degrees. UGC has approved online education, and degrees awarded by UGC-entitled universities are accepted for all government and private sector jobs.',
    display_order: 1,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    degree_id: null,
    question: 'Can I get a job after completing an online degree?',
    answer: 'Absolutely! Online degrees from recognized universities are accepted by all major companies. Many top recruiters like TCS, Infosys, Wipro, and multinational corporations actively hire candidates with online degrees.',
    display_order: 2,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    degree_id: null,
    question: 'Is there any age limit for online courses?',
    answer: 'No, there is no upper age limit for pursuing online degrees. Whether you are a working professional, homemaker, or fresh graduate - online education is open for everyone.',
    display_order: 3,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    degree_id: null,
    question: 'How are online exams conducted?',
    answer: 'Online exams are typically conducted through proctored online examination systems. You can take exams from home using a computer with webcam. Some universities also offer offline exam centers.',
    display_order: 4,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '5',
    degree_id: null,
    question: 'What is the admission process?',
    answer: 'Simple process: Fill enquiry form → Counsellor guidance → Submit documents online → Pay fee → Get enrolled. Complete within 2-3 working days.',
    display_order: 5,
    is_active: true,
    created_at: new Date().toISOString(),
  },
];

// Helper functions to get data
export function getDegrees() {
  return mockDegrees.filter(d => d.is_active);
}

export function getFeaturedDegrees() {
  return mockDegrees.filter(d => d.is_active && d.is_featured);
}

export function getDegreeBySlug(slug: string) {
  return mockDegrees.find(d => d.slug === slug && d.is_active);
}

export function getDegreesByCategory(category: string) {
  return mockDegrees.filter(d => d.category === category && d.is_active);
}

export function getPartnerUniversities() {
  return mockPartnerUniversities.filter(u => u.is_active).sort((a, b) => a.display_order - b.display_order);
}

export function getGeneralFAQs() {
  return mockFAQs.filter(f => f.degree_id === null && f.is_active);
}
